global:
  scrape_interval: 15s
  external_labels:
    monitor: "codelab-monitor"
scrape_configs:
  - job_name: "axum api"
    scrape_interval: 1s
    static_configs:
      - targets:
          - "node_exporter:9100"
